# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_num',
            field=models.CharField(default='000000000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
